apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    app.kubernetes.io/part-of: etl-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: nessie
  labels:
    app.kubernetes.io/part-of: etl-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: spark
  labels:
    app.kubernetes.io/part-of: etl-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    app.kubernetes.io/part-of: etl-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: airbyte
  labels:
    app.kubernetes.io/part-of: etl-stack
